blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/nsshewa/Donuts-As-A-Service/discussions
    about: Ask questions, share ideas, and discuss topics related to Donuts.